from django.urls import path, include
from . import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),

    path('register/',
         views.UserRegistrationView.as_view(),
         name='register'),
    path('edit/',
         views.UserEditView.as_view(),
         name='edit'),
    path('profile/<str:username>/',
         views.ProfileView.as_view(),
         name='profile'),
    path('follow/<str:username>/',
         views.FollowView.as_view(),
         name='follow'),
    path('users/',
         views.UserListView.as_view(),
         name='user_list'),
    path('send_friend_request/<int:to_user_id>/',
         views.SendFriendRequestView.as_view(),
         name='send_friend_request'),
    path('accept_friend_request/<int:friendship_id>/',
         views.AcceptFriendRequestView.as_view(),
         name='accept_friend_request'),
    path('reject_friend_request/<int:friendship_id>/',
         views.RejectFriendRequestView.as_view(),
         name='reject_friend_request'),
    path('friends/',
         views.FriendListView.as_view(),
         name='friend_list'),
    path('message/create/<int:recipient_id>/',
         views.CreateMessageView.as_view(),
         name='create_message'),
    path('conversation/<int:recipient_id>/',
         views.ConversationView.as_view(),
         name='conversation'),
    path('followers/<str:username>/',
         views.FollowersView.as_view(),
         name='followers'),
    path('following/<str:username>/',
         views.FollowingView.as_view(),
         name='following'),

]
